etitle: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
#remote_theme: just-the-docs
#theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
url: ""

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
